# Generated by Django 3.1.12 on 2025-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('Good', 'Good Habit'), ('Bad', 'Bad Habit')], default='Good', max_length=10),
        ),
    ]
